### ISSUE TITLE
Missing in Requirements

### ISSUE THREAD

**Issue by dodyg** [silverkeytech/house-care#1]
Identify which part of the house that require maintenance, e.g. plumbing, stove, tiles, lock, etc.

**Comment by dodyg** [comment]
> Feedback and Ratings: Tenants can provide feedback and ratings on the quality of maintenance work and service providers, helping landlords identify areas for improvement and recognize exceptional service.

Remove ratings and feedbacks

**Comment by dodyg** [comment]
> Reports and Analytics

Forget about analytics

**Comment by nourhanhelmy1** [comment]
Changes done in the proposal and we will be taking them into consideration when designing on Penpot.
